declare module '@vue/cli-shared-utils'
declare module 'validate-npm-package-name'
declare module '@vue/cli-shared-utils/lib/exit'
declare module '@vue/cli-shared-utils/lib/logger'
declare module '@vue/cli-shared-utils/lib/validate'
